### PR TITLE
Remove obsolete scripts

### PR DESCRIPTION
**Pull request by bill-long**
To address #920 and make it harder to accidentally run obsolete scripts, this PR:

* Removes the scripts from source.
* Changes the old docs page (these were written before we moved to the new docs, so we left it alone to avoid breaking links) to clearly call out that these are obsolete and point to the final release that included them.

Anything else we should do here? Should we also remove Test-ProxyLogon?

### CODE REVIEW

**Comment by dpaulson45** [comment]
Would be good to keep Test-ProxyLogon. It doesn't break anything if someone uses it. Good to keep around as an example source code for the next time we need to do something similar. 

Are we keeping EOMT since that appears to only do actions if on X build?

**Comment by bill-long** [comment]
Yeah, we are keeping EOMT.

**Review by lusassl-msft — DISMISSED** [review]
I'm okay with this change. Nothing to add/remove from my side.

**Comment by dbacon247** [comment]
EOMT won't break anything - although running it on the current builds of Exchange is not necessary it's only necessary for builds prior to the may 2021 CU if I recall - should be documented in the read me/help files. 

ExchangeMitgations.ps1 on the other hand did more drastic remediations such as turning of critical services in Exchange (also throughly documented) so that those who ran ExchangeMitigations.ps1 could roll back those changes and EOMT didn't account for those mitigations.

**Comment by dpaulson45** [comment]
@dbacon247 does that mean you approve this change? Waiting on you to approve it before merge.

**Review by dbacon247 — APPROVED** [review]

**Review by dpaulson45 — APPROVED** [review]

**Pull request merged**
