### PR TITLE
Add MFA Auth, new condition , Solution steps, feedback form at the nd of the script

### PR DESCRIPTION
**Pull request by hazemembaby**
**Issue:**
Describe what the issue is you are addressing
Add MFA Auth, new condition for DL checker, include Solution steps for each check, feedback form at the nd of the script

**Reason:**
Describe what the reason is for making the change
enhance the script for including more conditions and better proposing fixes for each condition

**Fix:**
Short description of the fix
Fixes will depend on each condition

**Validation:**
Provide if applicable

### CODE REVIEW

**Review by bill-long — CHANGES_REQUESTED** [review]
Where are the code changes? The only change here is a new comment.

**Comment by hazemembaby** [comment]
> Where are the code changes? The only change here is a new comment.

am still in the process of writing the code sorry if my PR was just containing a comment as I've created a new branch then that PR then unfortunately didn't have the time after to continue, if that's not OK I can close that PR and create a new PR when my code is ready for your review ?

**Comment by dpaulson45** [comment]
> > Where are the code changes? The only change here is a new comment.
> 
> am still in the process of writing the code sorry if my PR was just containing a comment as I've created a new branch then that PR then unfortunately didn't have the time after to continue, if that's not OK I can close that PR and create a new PR when my code is ready for your review ?

Just let us know when you are done making changes and are ready to merge. Next time, it would be best to just create the PR after you are ready to merge and have code to review.

**Comment by hazemembaby** [comment]
> > > Where are the code changes? The only change here is a new comment.
> > 
> > 
> > am still in the process of writing the code sorry if my PR was just containing a comment as I've created a new branch then that PR then unfortunately didn't have the time after to continue, if that's not OK I can close that PR and create a new PR when my code is ready for your review ?
> 
> Just let us know when you are done making changes and are ready to merge. Next time, it would be best to just create the PR after you are ready to merge and have code to review.

Am just testing the changes and shall get back to you on this week to merge am sorry If I made any confusion by that created PR!

**Review by bill-long — APPROVED** [review]
One thing you might consider is writing a function that both writes to host and writes to file, so you can de-duplicate all the output lines. However, that can be in a future PR.

**Review by bill-long — APPROVED** [review]

**Comment by bill-long** [comment]
Somehow this PR is no longer seeing changes from the source branch, as of about 3 days ago. There are changes more recent that don't appear here for whatever reason, but they are visible in the source branch. So, let's just close this PR and try again.

**Pull request closed without merging**
