### PR TITLE
Remove backtick to Analyzer logic code

### PR DESCRIPTION
**Pull request by dpaulson45**
Make the code easier to read and in a better format standard.

https://github.com/PoshCode/PowerShellPracticeAndStyle/blob/master/Style-Guide/Readability.md

### CODE REVIEW

**Review by lusassl-msft — APPROVED** [review]

**Comment by dpaulson45** [comment]
@lusassl-msft did you check in your Hybrid Lab as well? Pester testing works, but not sure if it covered all the display areas or not.

**Comment by lusassl-msft** [comment]
@dpaulson45 Pester should cover 95% of the cases. Will add the missing ones and confirm in hybrid lab. Will merge the PR when I’m done. Please give me 1-2 more days.

**Comment by dpaulson45** [comment]
> @dpaulson45 Pester should cover 95% of the cases. Will add the missing ones and confirm in hybrid lab. Will merge the PR when I’m done. Please give me 1-2 more days.

Okay, will wait to work on HC till we merge this change as it will just cause a bunch of conflicts otherwise.

**Comment by lusassl-msft** [comment]
Will do the confirmation work now.

**Pull request merged**
