### PR TITLE
Add new script that checks for Distribution Group eligibility for upgrade to O365group

### PR DESCRIPTION
**Pull request by hazemembaby**
**Issue:**
Describe what the issue is you are addressing
Building a script that is intended to check for Distribution Group eligibility for upgrade to
O365 Group by checking conditions listed on the below article and share the result onscreen & on a text file
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#which-distribution-lists-cannot-be-upgraded

**Reason:**
Describe what the reason is for making the change
To automate checks of the mentioned conditions on the article 

**Fix:**
Short description of the fix
Building a script that is intended to check for Distribution Group eligibility for upgrade to
O365 Group by checking conditions listed on the below article and share the result onscreen & on a text file
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#which-distribution-lists-cannot-be-upgraded

**Validation:**
Provide if applicable

### CODE REVIEW

**Review by bill-long — CHANGES_REQUESTED** [review]
Please run .build\CodeFormatter.ps1 -Save to fix the formatting issues. After that, there are some PSScriptAnalyzer fixes needed. Mostly we need to get rid of the global:

image

Also it says $Distgroup on line 108 is never used, and that appears to be correct. I don't see any use of that variable in the function.

**Comment by hazemembaby** [comment]
I've replaced the Global with Script scope variable and it passed the formatting issues using  .build\CodeFormatter.ps1 -Save however $Distgroup is declared among all my functions as illustrated below.
image

**Comment by bill-long** [comment]
@hazemembaby Yes, $Distgroup is fine everywhere _except_ line 108. That one doesn't get used. Look at the function that starts there. There is no $Distgroup anywhere in that function.

**Comment by bill-long** [comment]
Somehow it's still seeing a lot of formatting issues. Make sure you commit and push changes after CodeFormatter -Save.

**Comment by hazemembaby** [comment]
Regarding $Distgroup it's already added on the same function as illustrated

image

Not sure why it's still seeing these formatting issues any idea how to fix them?
image

**Comment by bill-long** [comment]
Try putting this on line 106 to suppress the unused parameter error:

```
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSReviewUnusedParameter', '', Justification = 'Incorrect rule result')]
```

**Review by bill-long — APPROVED** [review]

**Comment by hazemembaby** [comment]
Thank you @bill-long it went clear now after adding suppress message line provided by you!
image
image

**Comment by bill-long** [comment]
Looks good now!

**Pull request merged**
