### PR TITLE
Update MDOThreatPolicyChecker.ps1

### PR DESCRIPTION
**Pull request by rosspa05**
**Issue:**
Small test to check the contributor license agreement. 

**Reason:**
Small test to check the contributor license agreement. 

**Fix:**
Added a period at end of a single prompt. 

**Validation:**
Provide if applicable

@microsoft-github-policy-service terminate

### CODE REVIEW

**Comment by rosspa05** [comment]
@microsoft-github-policy-service terminate

**Review by bill-long — CHANGES_REQUESTED** [review]
Blocking this from merging so we can look at the CLA issue.

**Comment by bill-long** [comment]
@microsoft-github-policy-service rerun

**Comment by bill-long** [comment]
@microsoft-github-policy-service rerun

**Comment by bill-long** [comment]
@microsoft-github-policy-service rerun

**Review by bill-long — APPROVED** [review]

**Review by iserrano76 — APPROVED** [review]

**Pull request merged**
